### ISSUE TITLE
Kelvin, min and max values

### ISSUE THREAD

**Issue by gaetan-puleo** [jaames/iro.js#112] opened 2020-05-03 21:22 UTC
Hello, I want first to thank you for your lib, it's really useful.

I am working on a smart lights app.

I would have a slider with sliderType 'kelvin' and a min and a max options.

It's because some lights support only 6500 kelvins and it's strange to have a slider with a maximum of ~ 110000 kelvins.

**Comment by jaames** [comment] 2020-05-03 21:26
This is a duplicate of #105, here's what I said there:

> I forgot to document it (sorry!) but this is actually implemented!

> When creating the kelvin slider, you can set min and max temperature range:

> ```js
> var colorPicker = new iro.ColorPicker('#picker', {
> layout: [
>    { 
>      component: iro.ui.Slider,
>      options: {
>        sliderType: 'kelvin',
>        minTemperature: 2000,
>        maxTemperature: 30000,
>      }
>    },
>  ]
>});
>```

> The smallest possible temperature value is `1000`, the largest is `40000`.

> Again, sorry that's not documented!

**Closed by jaames** 2020-05-03 21:26 UTC

**Comment by gaetan-puleo** [comment] 2020-05-03 21:32
Thank you and sorry I didn't see this issue.

**Comment by jaames** [comment] 2020-05-03 21:35
It's no problem, tonight I'll try to update the iro.js website to include those options :)
